global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: deploy_bot
    static_configs:
      - targets: ["bot:9090"]
    metrics_path: /metrics

  - job_name: node_exporter
    static_configs:
      - targets: ["bot_host:9100"]
